version: "3.9"

services:
  db:
    image: mysql:8.0
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      TZ: Asia/Muscat   # this will use mucat time zone
      MYSQL_DATABASE: ${MYSQL_DATABASE:-appdb}
      MYSQL_USER: ${MYSQL_USER:-appuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-apppass}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "127.0.0.1",
          "-uroot",
          "-p${MYSQL_ROOT_PASSWORD:-rootpass}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    environment:
      DB_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USERNAME: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      APP_IMAGES_DIR: /opt/app/images
      SERVER_PORT: 8080
    volumes:
      - images:/opt/app/images
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: /api
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data:
  images:
